=== scientific-librarian/MALIS22_IT2_1.1_Bennemann/IT2.1_Bennemann/malis-it2-aufgabe1.1/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Wurzelschema",
  "description": "Dies ist das Wurzelschema, das die Schemas f√ºr die einzlenen Felder referenziert.",
  "type": "object",
  "required": ["@context", "gndIdentifier", "id", "preferredName", "type"],
  "properties": {
    "@context": {
      "$ref": "context-schema.json"
    },
    "id": {
      "$ref": "id.json"
    },
    "gndIdentifier": {
      "$ref": "gndIdentifier.json"
    },
    "type": {
      "$ref": "type.json"
    },
    "preferredName": {
      "$ref": "preferredName.json"
    },
    "variantName": {
      "$ref": "variantName.json"
    },
    "contributor": {
      "$ref": "professionOrOccupation.json"
    },
    "professionOrOccupation": {
      "$ref": "professionOrOccupation.json"
    },
    "gender": {
      "$ref": "gender.json"
    },
    "geographicAreaCode": {
      "$ref": "geographicAreaCode.json"
    }
  }
}

=== scientific-librarian/MALIS22_IT2_1.1_Bennemann/IT2.1_Bennemann/malis-it2-aufgabe1.1/examples/valid/1078122261.json
{
  "@context": "http://lobid.org/gnd/context.jsonld",
  "id": "https://d-nb.info/gnd/1078122261",
  "gndIdentifier": "1078122261",
  "type": [
    "Person",
    "AuthorityResource"
  ],
  "preferredName": "Blanco, Mykki",
  "variantName": [
    "Mykki Blanco",
    "Quattlebaum, Michael",
    "Quattlebaum, Michael David, Jr.",
    "Mykki, Rapmusiker"
  ],
  "professionOrOccupation": [
    {
      "id": "https://d-nb.info/gnd/4040841-3",
      "label": "Musiker"
    },
    {
      "id": "https://d-nb.info/gnd/7545699-0",
      "label": "Performancekünstler"
    },
    {
      "id": "https://d-nb.info/gnd/4053309-8",
      "label": "Schriftsteller"
    },
    {
      "id": "https://d-nb.info/gnd/4303534-6",
      "label": "Rapmusiker"
    }
  ],
  "gender": [
    {
      "id": "https://d-nb.info/standards/vocab/gnd/gender#male",
      "label": "Männlich"
    }
  ],
  "geographicAreaCode": [
    {
      "id": "https://d-nb.info/standards/vocab/gnd/geographic-area-code#XD-US",
      "label": "USA"
    }
  ]
}
